name: Lint

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16, 1.17, 1.18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Cache go
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          skip-pkg-cache: true
          skip-build-cache: true
          only-new-issues: true
          args: -v ./...
